Bansach/Models/DANHMUC.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bansach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANHMUC()
        {
            this.SACHes = new HashSet<SACH>();
        }
    
        public int Iddanhmuc { get; set; }
        public Nullable<int> Idloaisach { get; set; }
        public string Tendanhmuc { get; set; }
    
        public virtual LOAISACH LOAISACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SACH> SACHes { get; set; }
    }
}

Bansach/Areas/Admin/Controllers/DANHMUCsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bansach.Models;
using PagedList;

namespace Bansach.Areas.Admin.Controllers
{
    public class DANHMUCsController : Controller
    {
        private Bán_SáchEntities db = new Bán_SáchEntities();

        // GET: Admin/DANHMUCs
        public ActionResult Index(string SearchString, string currentFilter, int? page)
        {
            var DM = db.DANHMUCs.Include(d => d.LOAISACH).ToList();
            if (!String.IsNullOrEmpty(SearchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
            {
                DM = db.DANHMUCs.Where(n => n.Tendanhmuc.Contains(SearchString)).ToList(); //lọc theo chuỗi tìm kiếm
            }
            ViewBag.CurrentFilter = SearchString;
            int pageSize = 15;
            int PageNumber = (page ?? 1);
            return View(DM.ToPagedList(PageNumber, pageSize));
        }

        // GET: Admin/DANHMUCs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DANHMUC dANHMUC = db.DANHMUCs.Find(id);
            if (dANHMUC == null)
            {
                return HttpNotFound();
            }
            return View(dANHMUC);
        }

        // GET: Admin/DANHMUCs/Create
        public ActionResult Create()
        {
            ViewBag.Idloaisach = new SelectList(db.LOAISACHes, "Idloaisach", "Tenloaisach");
            return View();
        }

        // POST: Admin/DANHMUCs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Iddanhmuc,Idloaisach,Tendanhmuc")] DANHMUC dANHMUC)
        {
            if (ModelState.IsValid)
            {
                db.DANHMUCs.Add(dANHMUC);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Idloaisach = new SelectList(db.LOAISACHes, "Idloaisach", "Tenloaisach", dANHMUC.Idloaisach);
            return View(dANHMUC);
        }

        // GET: Admin/DANHMUCs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DANHMUC dANHMUC = db.DANHMUCs.Find(id);
            if (dANHMUC == null)
            {
                return HttpNotFound();
            }
            ViewBag.Idloaisach = new SelectList(db.LOAISACHes, "Idloaisach", "Tenloaisach", dANHMUC.Idloaisach);
            return View(dANHMUC);
        }

        // POST: Admin/DANHMUCs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Iddanhmuc,Idloaisach,Tendanhmuc")] DANHMUC dANHMUC)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dANHMUC).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Idloaisach = new SelectList(db.LOAISACHes, "Idloaisach", "Tenloaisach", dANHMUC.Idloaisach);
            return View(dANHMUC);
        }

        // GET: Admin/DANHMUCs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DANHMUC dANHMUC = db.DANHMUCs.Find(id);
            if (dANHMUC == null)
            {
                return HttpNotFound();
            }
            return View(dANHMUC);
        }

        // POST: Admin/DANHMUCs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DANHMUC dANHMUC = db.DANHMUCs.Find(id);
            db.DANHMUCs.Remove(dANHMUC);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bansach/Areas/Admin/Views/DANHMUCs/Create.cshtml
@model Bansach.Models.DANHMUC

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}
<div class="header-advance-area">
    <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="icon nalika-home"></i>
                                    </div>
                                    <div class="breadcomb-ctn">
                                        <h2>QUẢN LÝ DANH MỤC</h2>
                                        <p>Welcome to book library <span class="bread-ntd">admin template</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-report">
                                    <button data-toggle="tooltip" data-placement="left" title="download report" class="btn"><i class="icon nalika-download"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="single-product-tab-area mg-b-30">
    <!-- Single pro tab review Start-->
    <div class="single-pro-review-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="review-tab-pro-inner">
                        <ul id="myTab3" class="tab-review-design">
                            <li class="active"><a href="#description"><i class="icon nalika-edit" aria-hidden="true"></i>THÊM DANH MỤC</a></li>
                        </ul>
                        @*@using (Html.BeginForm("Create", "nhadat", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                            }*@

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                            <div class="review-content-section">
                                                <div class="input-group mg-b-pro-edt" style="width:505px">
                                                    <div class="form-group">
                                                        <div class="col-md-10">
                                                            <label style="color:white;">Tên loại sách</label>
                                                            @Html.DropDownList("Idloaisach", null, htmlAttributes: new { @class = "form-control" })
                                                            @Html.ValidationMessageFor(model => model.Idloaisach, "", new { @class = "text-danger" })
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="col-md-10">
                                                            <label style="color:white;">Tên danh mục</label>
                                                            @Html.EditorFor(model => model.Tendanhmuc, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.Tendanhmuc, "", new { @class = "text-danger" })
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="text-center custom-pro-edt-ds">


                                                <input type="submit" value="Lưu" class="btn btn-ctl-bt waves-effect waves-light m-r-10" />

                                                <button type="button" class="btn btn-ctl-bt waves-effect waves-light">
                                                    <div>
                                                        @Html.ActionLink("Quay lại", "Index")
                                                    </div>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Bansach/Areas/Admin/Views/DANHMUCs/Delete.cshtml
@model Bansach.Models.DANHMUC

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}
<div class="header-advance-area">
    <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="icon nalika-home"></i>
                                    </div>
                                    <div class="breadcomb-ctn">
                                        <h2>QUẢN LÝ DANH MỤC</h2>
                                        <p>Welcome to book library <span class="bread-ntd">admin template</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-report">
                                    <button data-toggle="tooltip" data-placement="left" title="download report" class="btn"><i class="icon nalika-download"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="product-status mg-b-30">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>XÓA DANH MỤC</h4>

                    <div>
                        <table>
                            <tr>
                                <th>Id danh mục</th>
                                <th>Tên loại sách</th>
                                <th>Tên danh mục</th>
                                <th></th>
                            </tr>

                            <tr>
                                <td>
                                    @Html.DisplayFor(model => model.Iddanhmuc)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.LOAISACH.Tenloaisach)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Tendanhmuc)
                                </td>
                            </tr>

                        </table>
                    </div>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="product-tab-list tab-pane fade active in" id="description">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="text-center custom-pro-edt-ds">
                                        <input Onclick="return confirm('Bạn thật sự muốn xóa?');" type="submit" name="actiondelete" value="Xóa" class="btn btn-default" style="background-color: #152036; color: #1b4b8e" />
                                        <button type="button" class="btn btn-ctl-bt waves-effect waves-light">
                                            <div>
                                                @Html.ActionLink("Quay lại", "Index")
                                            </div>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>

        </div>
    </div>
</div>

Bansach/Areas/Admin/Views/DANHMUCs/Details.cshtml
@model Bansach.Models.DANHMUC

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}
<div class="header-advance-area">
    <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="icon nalika-home"></i>
                                    </div>
                                    <div class="breadcomb-ctn">
                                        <h2>QUẢN LÝ DANH MỤC</h2>
                                        <p>Welcome to book library <span class="bread-ntd">admin template</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-report">
                                    <button data-toggle="tooltip" data-placement="left" title="download report" class="btn"><i class="icon nalika-download"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="product-status mg-b-30">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>XEM DANH MỤC</h4>

                    <div>
                        <table>
                            <tr>
                                <th>Id danh mục</th>
                                <th>Tên loại sách</th>
                                <th>Tên danh mục</th>
                                <th></th>
                            </tr>

                            <tr>
                                <td>
                                    @Html.DisplayFor(model => model.Iddanhmuc)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.LOAISACH.Tenloaisach)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Tendanhmuc)
                                </td>
                            </tr>

                        </table>
                    </div>

                    <div class="product-tab-list tab-pane fade active in" id="description">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="text-center custom-pro-edt-ds">
                                    <button type="button" class="btn btn-ctl-bt waves-effect waves-light">
                                        <div>
                                            @Html.ActionLink("Quay lại", "Index")
                                        </div>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Bansach/Areas/Admin/Views/DANHMUCs/Edit.cshtml
@model Bansach.Models.DANHMUC

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}
<div class="header-advance-area">
    <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="icon nalika-home"></i>
                                    </div>
                                    <div class="breadcomb-ctn">
                                        <h2>QUẢN LÝ DANH MỤC</h2>
                                        <p>Welcome to book library <span class="bread-ntd">admin template</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-report">
                                    <button data-toggle="tooltip" data-placement="left" title="download report" class="btn"><i class="icon nalika-download"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="single-product-tab-area mg-b-30">
    <!-- Single pro tab review Start-->
    <div class="single-pro-review-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="review-tab-pro-inner">
                        <ul id="myTab3" class="tab-review-design">
                            <li class="active"><a href="#description"><i class="icon nalika-edit" aria-hidden="true"></i>SỬA DANH MỤC</a></li>
                        </ul>


                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                            <div class="review-content-section">
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                @Html.HiddenFor(model => model.Iddanhmuc)
                                                <div class="input-group mg-b-pro-edt" style="width:505px">
                                                    <div class="form-group">
                                                        <div class="col-md-10">
                                                            <label style="color:white;">Tên loại sách</label>
                                                            @Html.DropDownList("Idloaisach", null, htmlAttributes: new { @class = "form-control" })
                                                            @Html.ValidationMessageFor(model => model.Idloaisach, "", new { @class = "text-danger" })
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="col-md-10">
                                                            <label style="color:white;">Tên danh mục</label>
                                                            @Html.EditorFor(model => model.Tendanhmuc, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.Tendanhmuc, "", new { @class = "text-danger" })
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="text-center custom-pro-edt-ds">
                                                <input type="submit" value="Cập nhật" class="btn btn-ctl-bt waves-effect waves-light m-r-10" />
                                                <button type="button" class="btn btn-ctl-bt waves-effect waves-light">
                                                    <div>
                                                        @Html.ActionLink("Quay lại", "Index")
                                                    </div>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Bansach/Areas/Admin/Views/DANHMUCs/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model PagedList.IPagedList<Bansach.Models.DANHMUC>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}
<div class="header-advance-area">
    <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="icon nalika-home"></i>
                                    </div>
                                    <div class="breadcomb-ctn">
                                        <h2>QUẢN LÝ DANH MỤC</h2>
                                        <p>Welcome to book library <span class="bread-ntd">admin template</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-report">
                                    <button data-toggle="tooltip" data-placement="left" title="download report" class="btn"><i class="icon nalika-download"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="product-status mg-b-30">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>DANH SÁCH DANH MỤC</h4>
                    <div class="add-product">
                        <a title="Thêm" class="fa fa-plus" aria-hidden="true">
                            <p> @Html.ActionLink("Thêm", "Create") </p>
                        </a>
                    </div>

                    @using (Html.BeginForm("Index", "DANHMUCs", FormMethod.Get))
                    {
                        <p>
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                            <input type="submit" value="Tìm kiếm" class="btn btn-ctl-bt waves-effect " style="background-color: #152036; height:28px; color:#ffffff" />
                        </p>
                    }

                    <table>
                        <tr>
                            <th>Id danh mục</th>
                            <th>Tên loại sách</th>
                            <th>Tên danh mục</th>
                            <th></th>
                        </tr>
                        @foreach (var item in Model)
                        {

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Iddanhmuc)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LOAISACH.Tenloaisach)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Tendanhmuc)
                        </td>

                        <td>
                            @Html.ActionLink("Sửa", "Edit", new { id = item.Iddanhmuc }) |
                            @Html.ActionLink("Xem", "Details", new { id = item.Iddanhmuc }) |
                            @Html.ActionLink("Xóa", "Delete", new { id = item.Iddanhmuc })
                        </td>

                    </tr>
                        }
                    </table>
                    <div class="custom-pagination">
                        <p style="color:#ffffff">Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>

                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, CurrenFilter = ViewBag.CurrenFilter }))
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>