Bansach/Models/SACH.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bansach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
            this.CHITIETHDBLs = new HashSet<CHITIETHDBL>();
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.TACGIAs = new HashSet<TACGIA>();
        }
    
        public int Idsach { get; set; }
        public Nullable<int> IdNXB { get; set; }
        public Nullable<int> Iddanhmuc { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string Tuasach { get; set; }
        public string Gioithieusach { get; set; }
        public Nullable<int> Khoiluong { get; set; }
        public Nullable<System.DateTime> Ngayphathanh { get; set; }
        public string Ngonngu { get; set; }
        public string Nguoidich { get; set; }
        public string Kichthuoc { get; set; }
        public Nullable<int> Sotrang { get; set; }
        public string Giagoc { get; set; }
        public string Giamgia { get; set; }
        public string Giaban { get; set; }
        public string Motangan { get; set; }
        public string Hinhanh { get; set; }
        public string Masach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHDBL> CHITIETHDBLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACGIA> TACGIAs { get; set; }
    }
}

Bansach/Areas/Admin/Controllers/SACHesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bansach.Models;
using PagedList;

namespace Bansach.Areas.Admin.Controllers
{
    public class SACHesController : Controller
    {
        private Bán_SáchEntities db = new Bán_SáchEntities();

        // GET: Admin/SACHes
        public ActionResult Index(string SearchString, string currentFilter, int? page)
        {
            var SACH = db.SACHes.Include(s => s.DANHMUC).Include(s => s.NHAXUATBAN).ToList();
            if (!String.IsNullOrEmpty(SearchString)) // kiểm tra chuỗi tìm kiếm có rỗng/null hay không
            {
                SACH = db.SACHes.Where(n => n.Tuasach.Contains(SearchString)).ToList(); //lọc theo chuỗi tìm kiếm
            }
            ViewBag.CurrentFilter = SearchString;
            int pageSize = 6;
            int PageNumber = (page ?? 1);
            return View(SACH.ToPagedList(PageNumber, pageSize));
        }

        // GET: Admin/SACHes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SACH sACH = db.SACHes.Find(id);
            if (sACH == null)
            {
                return HttpNotFound();
            }
            return View(sACH);
        }

        // GET: Admin/SACHes/Create
        public ActionResult Create()
        {
            ViewBag.Iddanhmuc = new SelectList(db.DANHMUCs, "Iddanhmuc", "Tendanhmuc");
            ViewBag.IdNXB = new SelectList(db.NHAXUATBANs, "IdNXB", "Ten");
            return View();
        }

        // POST: Admin/SACHes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Idsach,IdNXB,Iddanhmuc,Soluong,Tuasach,Gioithieusach,Khoiluong,Ngayphathanh,Ngonngu,Nguoidich,Kichthuoc,Sotrang,Giagoc,Giamgia,Giaban,Motangan,Hinhanh,Masach")] SACH sACH)
        {
            if (ModelState.IsValid)
            {
                db.SACHes.Add(sACH);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Iddanhmuc = new SelectList(db.DANHMUCs, "Iddanhmuc", "Tendanhmuc", sACH.Iddanhmuc);
            ViewBag.IdNXB = new SelectList(db.NHAXUATBANs, "IdNXB", "Ten", sACH.IdNXB);
            return View(sACH);
        }

        // GET: Admin/SACHes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SACH sACH = db.SACHes.Find(id);
            if (sACH == null)
            {
                return HttpNotFound();
            }
            ViewBag.Iddanhmuc = new SelectList(db.DANHMUCs, "Iddanhmuc", "Tendanhmuc", sACH.Iddanhmuc);
            ViewBag.IdNXB = new SelectList(db.NHAXUATBANs, "IdNXB", "Ten", sACH.IdNXB);
            return View(sACH);
        }

        // POST: Admin/SACHes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Idsach,IdNXB,Iddanhmuc,Soluong,Tuasach,Gioithieusach,Khoiluong,Ngayphathanh,Ngonngu,Nguoidich,Kichthuoc,Sotrang,Giagoc,Giamgia,Giaban,Motangan,Hinhanh,Masach")] SACH sACH)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sACH).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Iddanhmuc = new SelectList(db.DANHMUCs, "Iddanhmuc", "Tendanhmuc", sACH.Iddanhmuc);
            ViewBag.IdNXB = new SelectList(db.NHAXUATBANs, "IdNXB", "Ten", sACH.IdNXB);
            return View(sACH);
        }

        // GET: Admin/SACHes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SACH sACH = db.SACHes.Find(id);
            if (sACH == null)
            {
                return HttpNotFound();
            }
            return View(sACH);
        }

        // POST: Admin/SACHes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SACH sACH = db.SACHes.Find(id);
            db.SACHes.Remove(sACH);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bansach/Areas/Admin/Views/SACHes/Delete.cshtml
@model Bansach.Models.SACH

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}
<div class="header-advance-area">
    <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="icon nalika-home"></i>
                                    </div>
                                    <div class="breadcomb-ctn">
                                        <h2>QUẢN LÝ SÁCH</h2>
                                        <p>Welcome to book library <span class="bread-ntd">admin template</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-report">
                                    <button data-toggle="tooltip" data-placement="left" title="download report" class="btn"><i class="icon nalika-download"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="product-status mg-b-30">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>XÓA SÁCH</h4>

                    <div>
                        <table>
                            <tr>
                                <th>Tựa sách</th>
                                <th>Giới thiệu sách</th>
                                <th>Khối lượng</th>
                                <th>Ngôn ngữ</th>
                                <th>Người dịch</th>
                                <th>Kích thước</th>
                                <th>Số lượng</th>
                                <th>Ngày phát hành</th>
                                <th>Số trang</th>
                                <th>Giá gốc</th>
                                <th>Giảm giá</th>
                                <th>Giá bán</th>
                                <th>Mô tả ngắn</th>
                                <th>Hình ảnh</th>
                                <th>Mã sách</th>
                                <th>Tên danh mục</th>
                                <th>Nhà xuất bản</th>
                                <th></th>
                            </tr>

                            <tr>
                                <td>
                                    @Html.DisplayNameFor(model => model.Tuasach)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Gioithieusach)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Khoiluong)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Ngonngu)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Nguoidich)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Kichthuoc)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Soluong)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Ngayphathanh)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Sotrang)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Giaban)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Giagoc)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Giamgia)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Motangan)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Hinhanh)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Masach)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.DANHMUC.Tendanhmuc)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.NHAXUATBAN.Ten)
                                </td>
                            </tr>

                        </table>
                    </div>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="product-tab-list tab-pane fade active in" id="description">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="text-center custom-pro-edt-ds">
                                        <input Onclick="return confirm('Bạn thật sự muốn xóa?');" type="submit" name="actiondelete" value="Xóa" class="btn btn-default" style="background-color: #152036; color: #1b4b8e" />
                                        <button type="button" class="btn btn-ctl-bt waves-effect waves-light">
                                            <div>
                                                @Html.ActionLink("Quay lại", "Index")
                                            </div>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>

        </div>
    </div>
</div>

Bansach/Areas/Admin/Views/SACHes/Details.cshtml
@model Bansach.Models.SACH

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}
<div class="header-advance-area">
    <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="icon nalika-home"></i>
                                    </div>
                                    <div class="breadcomb-ctn">
                                        <h2>QUẢN LÝ SÁCH</h2>
                                        <p>Welcome to book library <span class="bread-ntd">admin template</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-report">
                                    <button data-toggle="tooltip" data-placement="left" title="download report" class="btn"><i class="icon nalika-download"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="product-status mg-b-30">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>XEM SÁCH</h4>

                    <div>
                        <table>
                            <tr>
                                <th>Tựa sách</th>
                                <th>Giới thiệu sách</th>
                                <th>Khối lượng</th>
                                <th>Ngôn ngữ</th>
                                <th>Người dịch</th>
                                <th>Kích thước</th>
                                <th>Số lượng</th>
                                <th>Ngày phát hành</th>
                                <th>Số trang</th>
                                <th>Giá gốc</th>
                                <th>Giảm giá</th>
                                <th>Giá bán</th>
                                <th>Mô tả ngắn</th>
                                <th>Hình ảnh</th>
                                <th>Mã sách</th>
                                <th>Tên danh mục</th>
                                <th>Nhà xuất bản</th>
                                <th></th>
                            </tr>

                            <tr>
                                <td>
                                    @Html.DisplayNameFor(model => model.Tuasach)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Gioithieusach)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Khoiluong)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Ngonngu)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Nguoidich)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Kichthuoc)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Soluong)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Ngayphathanh)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Sotrang)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Giaban)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Giagoc)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Giamgia)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Motangan)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Hinhanh)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.Masach)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.DANHMUC.Tendanhmuc)
                                </td>
                                <td>
                                    @Html.DisplayFor(model => model.NHAXUATBAN.Ten)
                                </td>
                            </tr>

                        </table>
                    </div>

                    <div class="product-tab-list tab-pane fade active in" id="description">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="text-center custom-pro-edt-ds">
                                    <button type="button" class="btn btn-ctl-bt waves-effect waves-light">
                                        <div>
                                            @Html.ActionLink("Quay lại", "Index")
                                        </div>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Bansach/Areas/Admin/Views/SACHes/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model PagedList.IPagedList<Bansach.Models.SACH>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutAdmin.cshtml";
}
<div class="header-advance-area">
    <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-wp">
                                    <div class="breadcomb-icon">
                                        <i class="icon nalika-home"></i>
                                    </div>
                                    <div class="breadcomb-ctn">
                                        <h2>QUẢN LÝ SÁCH</h2>
                                        <p>Welcome to book library <span class="bread-ntd">admin template</span></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="breadcomb-report">
                                    <button data-toggle="tooltip" data-placement="left" title="download report" class="btn"><i class="icon nalika-download"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="product-status mg-b-30">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="product-status-wrap">
                    <h4>DANH SÁCH SÁCH</h4>
                    <div class="add-product">
                        <a title="Thêm" class="fa fa-plus" aria-hidden="true">
                            <p> @Html.ActionLink("Thêm", "Create") </p>
                        </a>
                    </div>

                    @using (Html.BeginForm("Index", "SACHes", FormMethod.Get))
                    {
                        <p>
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                            <input type="submit" value="Tìm kiếm" class="btn btn-ctl-bt waves-effect " style="background-color: #152036; height:28px; color:#ffffff" />
                        </p>
                    }

                <table>
                    <tr>
                        <th>Tựa sách</th>
                        <th>Số lượng</th>
                        <th>Ngày phát hành</th>
                        <th>Số trang</th>
                        <th>Giá bán</th>
                        <th>Mô tả ngắn</th>
                        <th>Hình ảnh</th>
                        <th>Mã sách</th>
                        <th>Tên danh mục</th>
                        <th>Nhà xuất bản</th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Tuasach)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Soluong)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ngayphathanh)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sotrang)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Giaban)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Motangan)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Hinhanh)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Masach)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DANHMUC.Tendanhmuc)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NHAXUATBAN.Ten)
                            </td>
                            <td>
                                @Html.ActionLink("Sửa", "Edit", new { id = item.Idsach }) |
                                @Html.ActionLink("Xem", "Details", new { id = item.Idsach }) |
                                @Html.ActionLink("Xóa", "Delete", new { id = item.Idsach })
                            </td>

                        </tr>
                        }
                    </table>
                    <div class="custom-pagination">
                        <p style="color:#ffffff">Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>

                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, CurrenFilter = ViewBag.CurrenFilter }))
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>